# Generated by Django 2.1.4 on 2018-12-10 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.TextField(max_length=5000)),
                ('stime', models.DateField()),
                ('ftime', models.DateField()),
                ('ctime', models.DateField(auto_now_add=True)),
                ('rtime', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity_type',
            fields=[
                ('name', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Mnotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=200)),
                ('time', models.DateField(auto_now_add=True)),
                ('is_delete', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(auto_now_add=True)),
                ('act_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.Activity')),
            ],
        ),
        migrations.CreateModel(
            name='Sysnotice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('time', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True)),
                ('passwd_hash', models.CharField(default='123456', max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(max_length=2)),
                ('power', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='sysnotice',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.User'),
        ),
        migrations.AddField(
            model_name='registration',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.User'),
        ),
        migrations.AddField(
            model_name='mnotice',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.User'),
        ),
        migrations.AddField(
            model_name='activity',
            name='act_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.Activity_type'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='activity.User'),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('user_id', 'act_id')},
        ),
    ]
