# Generated by Django 2.1.4 on 2018-12-30 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20181227_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='point',
            field=models.FloatField(default=0),
        ),
    ]
