# Generated by Django 2.1.4 on 2018-12-14 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0002_auto_20181210_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='act_type',
            field=models.CharField(max_length=10),
        ),
        migrations.DeleteModel(
            name='Activity_type',
        ),
    ]
