# Generated by Django 2.1.4 on 2018-12-30 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_activity_point'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='is_freeze',
            field=models.BooleanField(default=False),
        ),
    ]
