# Generated by Django 2.1.4 on 2018-12-26 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_auto_20181214_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='max_num',
            field=models.IntegerField(default=10000),
        ),
    ]
