# Generated by Django 2.1.4 on 2018-12-30 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_is_freeze'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mnotice',
            name='user_id',
        ),
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-rtime']},
        ),
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['-time']},
        ),
        migrations.AlterModelOptions(
            name='sysnotice',
            options={'ordering': ['-time']},
        ),
        migrations.DeleteModel(
            name='Mnotice',
        ),
    ]
