# Generated by Django 2.1.4 on 2018-12-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0004_activity_max_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='max_num',
            field=models.IntegerField(),
        ),
    ]
